### ISSUE TITLE
Problems with - in ingredients lines

### ISSUE THREAD

**Issue by WhyMe4** [tmayoff/obsidian-meals#117]
[Crock Pot Low Carb Veggie Lasagna.md](https://github.com/user-attachments/files/16169599/Crock.Pot.Low.Carb.Veggie.Lasagna.md)

The attached recipe has lots of issues. If you remove the - (\-) at the start of the lines, it is better, but the - in the ingredients is causing issues.

**Comment by tmayoff** [comment]
So I found a few bugs from that file, I split them out into their own issues since they're all somewhat unrelated. I'm not sure if I missed anything but I'll start with these. What are the issues? Wrong entries in the shopping list? 

- https://github.com/tmayoff/obsidian-meals/issues/118
- https://github.com/tmayoff/obsidian-meals/issues/119
- https://github.com/tmayoff/obsidian-meals/issues/120

Somewhat unrelated all of the `-` are actually `\-` like they were escaped at some point, where did you get the recipe? Is this intentional? If it came from a website may I suggest the new downloader in the command palette (to try out at least) it'll download it formatted slightly differently from the files you've been sending me but simpler things like the '\-' shouldn't happen

**Comment by WhyMe4** [comment]
I think you got all the issues. 
I'm not sure where that recipe came from. I used to use Evernote, and that one was migrated to Obsidian.
I do get there might be some necessary manual clean up on my (the user) side as the code cannot account for all possibilities.

I've just been posting things as I run across them. If they are considered user error, I have no issue with that. Just let me know.

**Comment by tmayoff** [comment]
Things like the `\-` I'd consider 'unsupported' but they do work since I just skip to past the `-`. Everything else are actual bugs in the code. For any issues I will mention if it's just necessary to cleanup vs something that can/should be addressed by the plugin

**Comment by tmayoff** [comment]
Okay so I've cleaned up the issues, however for this line `- For serving: Parmesan cheese, freshly chopped herbs such as basil or parsley`. I'm going to say needs to be reformatted (at least for now). This is an updated version of the recipe

```markdown
#Untested #Italian #Main-Dish #Crock-Pot

**YIELD:** 6 servings

**PREP TIME:** 30 minutes

**TOTAL TIME:** 3 to 4 hours

## Ingredients
- 2 medium zucchini
- 1 medium eggplant
- Kosher salt
- 16 ounces (2 cups) good-quality store-bought tomato-based pasta sauce (or homemade)
- 1 medium red onion, diced
- 1 red bell pepper, diced
- 16 ounces low-fat cottage cheese (do not use skim—I used 1%)
- 2 large eggs
- 8 ounces part-skim shredded mozzarella or provolone cheese, divided (about 2 cups—I used a blend of both cheeses)
### For Serving:
- Parmesan cheese
- Freshly chopped herbs such as basil or parsley

## Directions
- With a mandoline or very sharp knife, slice the eggplant and zucchini length-wise into long, thin (1/4-inch) sections so that they resemble lasagna noodles. Spread the vegetable slices out onto a kitchen towel or layers of paper towels and sprinkle them lightly with kosher salt. Let stand for 15 minutes to allow some of the excess liquid to drain off. Pat dry. Prepare the zucchini and eggplant according to one of the three methods below:
    - GRILL METHOD: Preheat an outdoor grill or indoor grill pan to medium. Lightly coat the grill with canola oil, then grill the eggplant and zucchini strips until cooked and lightly brown, about 2 to 3 minutes per side.
    - BROIL METHOD: Place the top oven rack about 5 inches from the upper heat element. Set the oven to broil at 500 degrees F. Arrange the zucchini and eggplant slices in a single layer on a baking sheet. (Do not line the baking sheet pans with wax paper or parchment, as they will burn.) Lightly brush the slices with olive oil and season with salt and pepper. Flip over the slices and repeat for the other side. Broil for 8 minutes, or until lightly brown, working in multiple batches as needed. Remove from the oven and allow to cool slightly. Place the slices on paper towels to remove excess moisture.
    - NEITHER: Move ahead with the recipe—skip grilling or broiling the zucchini completely. The lasagna will have a lot of excess liquid around the veggie slices in the slow cooker (even after salting them in step 1), but if this doesn’t bother you, you can scoop out the noodles and discard it.
- Lightly coat a 6-quart crock pot with nonstick spray. Spread 1/2 cup tomato sauce on the bottom of the crock pot—the layer will seem very thin. In a small bowl, beat the cottage cheese together with the eggs.
- Create the first veggie lasagna layer in the crock pot as follows: 1 layer of eggplant “noodles”; one-third of the cottage cheese (about 2/3 cup); one-third of the bell peppers and onions; one-third of the mozzarella; 1/2 cup tomato sauce.
- Create the second veggie lasagna layer, this time using zucchini: 1 layer of zucchini “noodles”; one-third of the cottage cheese; one-third of the bell peppers and onions; one-third of the mozzarella; 1/2 cup of tomato sauce.
- Create the final layer: 1 layer of eggplant “noodles”; remaining cottage cheese; remaining bell peppers and onions; 1 layer of zucchini noodles; 1/2 cup tomato sauce; remaining mozzarella.
- Cover the crock pot and cook on high for 2 to 3 hours, until the eggplant is tender. To test, insert a long, thin knife into the lasagna and ensure the eggplant feels tender. Re-cover, turn off the slow cooker, and let stand until any remaining liquid is absorbed, about 30 minutes to 1 hour. (Note: if you did not grill or broil the vegetables first, you will have a lot of remaining liquid.) To serve, slice and scoop desired portions, then sprinkle with Parmesan cheese and herbs as desired.

source: http://www.wellplated.com/low-carb-lasagna/

SERVING: 6 
CALORIES: 273kcal; CARBOHYDRATES: 22g; PROTEIN: 23g; FAT: 12g; FIBER: 6g
```

**Comment by tmayoff** [comment]
I'll close this for now, if there's anything I missed feel free to open a new issue

**Comment by WhyMe4** [comment]
If I use your version it works well, but I just remove the - from the first character of the ingredients, it's still having issues. Recipe #Untested #Italian #Main-Dish #Crock-Pot **YIELD:** 6 servings **PREP TIME:** 30 minutes **TOTAL TIME:** 3 to 4 hours ### Ingredients 2 medium zucchini 1 medium eggplant Kosher salt 16 ounces (2 cups) good-quality store-bought tomato-based pasta sauce (or homemade) 1 medium red onion, diced 1 red bell pepper, diced 16 ounces low-fat cottage cheese (do not use skim—I used 1%) 2 large eggs 8 ounces part-skim shredded mozzarella or provolone cheese, divided (about 2 cups—I used a blend of both cheeses) For serving: Parmesan cheese, freshly chopped herbs such as basil or parsley ### Directions \- With a mandoline or very sharp knife, slice the eggplant and zucchini length-wise into long, thin (1/4-inch) sections so that they resemble lasagna noodles. Spread the vegetable slices out onto a kitchen towel or layers of paper towels and sprinkle them lightly with kosher salt. Let stand for 15 minutes to allow some of the excess liquid to drain off. Pat dry. Prepare the zucchini and eggplant according to one of the three methods below: - GRILL METHOD: Preheat an outdoor grill or indoor grill pan to medium. Lightly coat the grill with canola oil, then grill the eggplant and zucchini strips until cooked and lightly brown, about 2 to 3 minutes per side. - BROIL METHOD: Place the top oven rack about 5 inches from the upper heat element. Set the oven to broil at 500 degrees F. Arrange the zucchini and eggplant slices in a single layer on a baking sheet. (Do not line the baking sheet pans with wax paper or parchment, as they will burn.) Lightly brush the slices with olive oil and season with salt and pepper. Flip over the slices and repeat for the other side. Broil for 8 minutes, or until lightly brown, working in multiple batches as needed. Remove from the oven and allow to cool slightly. Place the slices on paper towels to remove excess moisture. - NEITHER: Move ahead with the recipe—skip grilling or broiling the zucchini completely. The lasagna will have a lot of excess liquid around the veggie slices in the slow cooker (even after salting them in step 1), but if this doesn’t bother you, you can scoop out the noodles and discard it. \- Lightly coat a 6-quart crock pot with nonstick spray. Spread 1/2 cup tomato sauce on the bottom of the crock pot—the layer will seem very thin. In a small bowl, beat the cottage cheese together with the eggs. \- Create the first veggie lasagna layer in the crock pot as follows: 1 layer of eggplant “noodles”; one-third of the cottage cheese (about 2/3 cup); one-third of the bell peppers and onions; one-third of the mozzarella; 1/2 cup tomato sauce. \- Create the second veggie lasagna layer, this time using zucchini: 1 layer of zucchini “noodles”; one-third of the cottage cheese; one-third of the bell peppers and onions; one-third of the mozzarella; 1/2 cup of tomato sauce. \- Create the final layer: 1 layer of eggplant “noodles”; remaining cottage cheese; remaining bell peppers and onions; 1 layer of zucchini noodles; 1/2 cup tomato sauce; remaining mozzarella. \- Cover the crock pot and cook on high for 2 to 3 hours, until the eggplant is tender. To test, insert a long, thin knife into the lasagna and ensure the eggplant feels tender. Re-cover, turn off the slow cooker, and let stand until any remaining liquid is absorbed, about 30 minutes to 1 hour. (Note: if you did not grill or broil the vegetables first, you will have a lot of remaining liquid.) To serve, slice and scoop desired portions, then sprinkle with Parmesan cheese and herbs as desired. source: http://www.wellplated.com/low-carb-lasagna/ SERVING: 6 CALORIES: 273kcal; CARBOHYDRATES: 22g; PROTEIN: 23g; FAT: 12g; FIBER: 6g Generates this shopping list - [ ] Kosher salt 0 - [ ] quality store-bought tomato-based pasta sauce (or homemade) - [ ] red onion, diced 1 medium - [ ] red bell pepper, diced 1 - [ ] fat cottage cheese (do not use skim—I used 1%) - [ ] eggs 2 large - [ ] skim shredded mozzarella or provolone cheese, divided (about 2 cups—I used a blend of both cheeses) On Jul 12, 2024, at 9:36 PM, Tyler ***@***.***> wrote: Okay so I've cleaned up the issues, however for this line - For serving: Parmesan cheese, freshly chopped herbs such as basil or parsley . I'm going to say needs to be reformatted (at least for now). This is an updated version of the recipe #Untested #Italian #Main-Dish #Crock-Pot ** YIELD: ** 6 servings ** PREP TIME: ** 30 minutes ** TOTAL TIME: ** 3 to 4 hours ## Ingredients - 2 medium zucchini - 1 medium eggplant - Kosher salt - 16 ounces (2 cups) good-quality store-bought tomato-based pasta sauce (or homemade) - 1 medium red onion, diced - 1 red bell pepper, diced - 16 ounces low-fat cottage cheese (do not use skim—I used 1%) - 2 large eggs - 8 ounces part-skim shredded mozzarella or provolone cheese, divided (about 2 cups—I used a blend of both cheeses) ### For Serving: - Parmesan cheese - Freshly chopped herbs such as basil or parsley ## Directions - With a mandoline or very sharp knife, slice the eggplant and zucchini length-wise into long, thin (1/4-inch) sections so that they resemble lasagna noodles. Spread the vegetable slices out onto a kitchen towel or layers of paper towels and sprinkle them lightly with kosher salt. Let stand for 15 minutes to allow some of the excess liquid to drain off. Pat dry. Prepare the zucchini and eggplant according to one of the three methods below: - GRILL METHOD: Preheat an outdoor grill or indoor grill pan to medium. Lightly coat the grill with canola oil, then grill the eggplant and zucchini strips until cooked and lightly brown, about 2 to 3 minutes per side. - BROIL METHOD: Place the top oven rack about 5 inches from the upper heat element. Set the oven to broil at 500 degrees F. Arrange the zucchini and eggplant slices in a single layer on a baking sheet. (Do not line the baking sheet pans with wax paper or parchment, as they will burn.) Lightly brush the slices with olive oil and season with salt and pepper. Flip over the slices and repeat for the other side. Broil for 8 minutes, or until lightly brown, working in multiple batches as needed. Remove from the oven and allow to cool slightly. Place the slices on paper towels to remove excess moisture. - NEITHER: Move ahead with the recipe—skip grilling or broiling the zucchini completely. The lasagna will have a lot of excess liquid around the veggie slices in the slow cooker (even after salting them in step 1), but if this doesn’t bother you, you can scoop out the noodles and discard it. - Lightly coat a 6-quart crock pot with nonstick spray. Spread 1/2 cup tomato sauce on the bottom of the crock pot—the layer will seem very thin. In a small bowl, beat the cottage cheese together with the eggs. - Create the first veggie lasagna layer in the crock pot as follows: 1 layer of eggplant “noodles”; one-third of the cottage cheese (about 2/3 cup); one-third of the bell peppers and onions; one-third of the mozzarella; 1/2 cup tomato sauce. - Create the second veggie lasagna layer, this time using zucchini: 1 layer of zucchini “noodles”; one-third of the cottage cheese; one-third of the bell peppers and onions; one-third of the mozzarella; 1/2 cup of tomato sauce. - Create the final layer: 1 layer of eggplant “noodles”; remaining cottage cheese; remaining bell peppers and onions; 1 layer of zucchini noodles; 1/2 cup tomato sauce; remaining mozzarella. - Cover the crock pot and cook on high for 2 to 3 hours, until the eggplant is tender. To test, insert a long, thin knife into the lasagna and ensure the eggplant feels tender. Re-cover, turn off the slow cooker, and let stand until any remaining liquid is absorbed, about 30 minutes to 1 hour. (Note: if you did not grill or broil the vegetables first, you will have a lot of remaining liquid.) To serve, slice and scoop desired portions, then sprinkle with Parmesan cheese and herbs as desired. source: http://www.wellplated.com/low-carb-lasagna/ SERVING: 6 CALORIES: 273kcal; CARBOHYDRATES: 22g; PROTEIN: 23g; FAT: 12g; FIBER: 6g — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you authored the thread. Message ID: ***@***.***>
